{{- if .Values.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: sandbox-operator-selfsigned
  namespace: {{ .Values.namespace }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sandbox-operator-serving-cert
  namespace: {{ .Values.namespace }}
spec:
  secretName: {{ .Values.webhook.tlsSecretName }}
  dnsNames:
    - sandbox-operator-webhook.{{ .Values.namespace }}.svc
    - sandbox-operator-webhook.{{ .Values.namespace }}.svc.cluster.local
  issuerRef:
    name: sandbox-operator-selfsigned
    kind: Issuer
{{- end }}
